<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Norevia_Startup_Manager_Lite</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	 <ApplicationManifest>app.manifest</ApplicationManifest>
	  <EnableWindowsTargeting>true</EnableWindowsTargeting>
	  <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Components\" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
